<?php
/**
 * acf-setup.php
 *
 * @package _s
 */

if ( WP_LOCAL_DEV ) {
  return;
}

// hide field group menu from users
if ( wp_get_current_user()->user_login !== 'sean' ) {
  define( 'ACF_LITE' , true );
}

/*
ACF field groups
 */
// export field export code here:
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_57450f989c97a',
  'title' => 'Category Page Fields',
  'fields' => array (
    array (
      'key' => 'field_5745107893aa3',
      'label' => 'Category Gallery',
      'name' => 'category_gallery',
      'type' => 'gallery',
      'instructions' => 'Upload images to display in the category\'s gallery.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'min' => 3,
      'max' => '',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => 'jpg,jpeg,webp',
      'insert' => 'append',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-templates/category-page.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_5776cb4951a0a',
  'title' => 'CTA Fields',
  'fields' => array (
    array (
      'key' => 'field_5776cb4ee25e3',
      'label' => 'CTA Link',
      'name' => 'cta_link',
      'type' => 'post_object',
      'instructions' => 'Select a page for the CTA to link to.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'id',
      'ui' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'cta',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_574500170290d',
  'title' => 'Home Page Fields',
  'fields' => array (
    array (
      'key' => 'field_5745002d2a79d',
      'label' => 'Home Sections',
      'name' => 'home_sections',
      'type' => 'flexible_content',
      'instructions' => 'Add home sections by clicking "Add Section" below.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Section',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '5745007fc6ee6',
          'name' => 'headline_section',
          'label' => 'Headline Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_574500b52a79e',
              'label' => 'Section Headline',
              'name' => 'section_headline',
              'type' => 'text',
              'instructions' => 'Enter a headline for the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_5745012e2a79f',
              'label' => 'Section Text',
              'name' => 'section_text',
              'type' => 'textarea',
              'instructions' => 'Enter some text to appear in the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => 3,
              'new_lines' => 'wpautop',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '574501dc784f2',
          'name' => 'product_category_section',
          'label' => 'Product Category Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_57450203784f3',
              'label' => 'Product Categories',
              'name' => 'product_categories',
              'type' => 'repeater',
              'instructions' => 'Add categories by clicking "Add Category" below.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 4,
              'max' => 4,
              'layout' => 'row',
              'button_label' => 'Add Category',
              'sub_fields' => array (
                array (
                  'key' => 'field_574502680527c',
                  'label' => 'Category Icon',
                  'name' => 'category_icon',
                  'type' => 'image',
                  'instructions' => 'Upload an icon for the category.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array (
                  'key' => 'field_5745028c0527d',
                  'label' => 'Category Title',
                  'name' => 'category_title',
                  'type' => 'text',
                  'instructions' => 'Enter the category\'s title.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_574502a80527e',
                  'label' => 'Category Text',
                  'name' => 'category_text',
                  'type' => 'textarea',
                  'instructions' => 'Enter some text describing the product category.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 5,
                  'new_lines' => 'wpautop',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_574502cf0527f',
                  'label' => 'Category Link',
                  'name' => 'category_link',
                  'type' => 'post_object',
                  'instructions' => 'Select a page for the category to link to.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'post_type' => array (
                    0 => 'page',
                  ),
                  'taxonomy' => array (
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'return_format' => 'id',
                  'ui' => 1,
                ),
              ),
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '57450618ae087',
          'name' => 'testimonial_section',
          'label' => 'Testimonial Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_57450621ae088',
              'label' => 'Testimonials',
              'name' => 'testimonials',
              'type' => 'relationship',
              'instructions' => 'Select the testimonials you\'d like to display in the section.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
                0 => 'testimonial',
              ),
              'taxonomy' => array (
              ),
              'filters' => array (
                0 => 'search',
              ),
              'elements' => '',
              'min' => 3,
              'max' => 10,
              'return_format' => 'object',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5745073e67fc0',
          'name' => 'image_cta_section',
          'label' => 'Image CTA Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_574507ad67fc1',
              'label' => 'CTA Items',
              'name' => 'cta_items',
              'type' => 'repeater',
              'instructions' => 'Add CTA items by clicking "Add CTA" below.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 2,
              'max' => 2,
              'layout' => 'row',
              'button_label' => 'Add CTA',
              'sub_fields' => array (
                array (
                  'key' => 'field_576d60f11ebd2',
                  'label' => 'CTA Image',
                  'name' => 'cta_image',
                  'type' => 'image',
                  'instructions' => 'Upload an image to use for the CTA item.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array (
                  'key' => 'field_5745082767fc2',
                  'label' => 'CTA Headline',
                  'name' => 'cta_headline',
                  'type' => 'text',
                  'instructions' => 'Enter a headline for the CTA.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_5745084467fc3',
                  'label' => 'CTA Text',
                  'name' => 'cta_text',
                  'type' => 'textarea',
                  'instructions' => 'Enter some text for the CTA.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 6,
                  'new_lines' => 'wpautop',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
                array (
                  'key' => 'field_574508a367fc4',
                  'label' => 'CTA Link',
                  'name' => 'cta_link',
                  'type' => 'post_object',
                  'instructions' => 'Select a page for the category to link to.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'post_type' => array (
                    0 => 'page',
                  ),
                  'taxonomy' => array (
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'return_format' => 'id',
                  'ui' => 1,
                ),
              ),
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5745098f5d631',
          'name' => 'text_cta_section',
          'label' => 'Text CTA Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_574509ab5d632',
              'label' => 'Section Headline',
              'name' => 'section_headline',
              'type' => 'text',
              'instructions' => 'Enter a headline for the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_574509da5d633',
              'label' => 'Section Text',
              'name' => 'section_text',
              'type' => 'textarea',
              'instructions' => 'Enter some text to appear in the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => 3,
              'new_lines' => 'wpautop',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_57450a815d634',
              'label' => 'CTA Link',
              'name' => 'cta_link',
              'type' => 'post_object',
              'instructions' => 'Select a page for the CTA to link to.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
                0 => 'page',
              ),
              'taxonomy' => array (
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'return_format' => 'id',
              'ui' => 1,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '57450b13fa792',
          'name' => 'banner_section',
          'label' => 'Banner Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_57450b42fa793',
              'label' => 'Banner Icon',
              'name' => 'banner_icon',
              'type' => 'image',
              'instructions' => 'Upload an icon to use above the banner headline.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array (
              'key' => 'field_57450bbefa794',
              'label' => 'Banner Headline',
              'name' => 'banner_headline',
              'type' => 'text',
              'instructions' => 'Enter the banner headline.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_57709af3a7f0e',
              'label' => 'Banner Link',
              'name' => 'banner_link',
              'type' => 'post_object',
              'instructions' => 'Select a page for the banner to link to.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
                0 => 'page',
              ),
              'taxonomy' => array (
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'return_format' => 'id',
              'ui' => 1,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-templates/home-page.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
  ),
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_57709f85c5722',
  'title' => 'Page Title Field',
  'fields' => array (
    array (
      'key' => 'field_57709f99c53be',
      'label' => 'Custom Page Title',
      'name' => 'custom_page_title',
      'type' => 'text',
      'instructions' => 'Add a custom page title. This should be used when you\'d like a longer title for the page, but would like to keep a simple title in the back-end. Example: a "Products" page in the dashboard with a title "Check Out Our Products." ',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_575e13da14e27',
  'title' => 'Products Page Fields',
  'fields' => array (
    array (
      'key' => 'field_575e147d1cc60',
      'label' => 'Product Categories',
      'name' => 'product_categories',
      'type' => 'repeater',
      'instructions' => 'Add product categories by clicking "Add Row" below.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 1,
      'max' => '',
      'layout' => 'row',
      'button_label' => 'Add Category',
      'sub_fields' => array (
        array (
          'key' => 'field_575e14b61cc61',
          'label' => 'Category Title',
          'name' => 'category_title',
          'type' => 'text',
          'instructions' => 'Enter the title of the category',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_575e14d51cc62',
          'label' => 'Category Photo',
          'name' => 'category_photo',
          'type' => 'image',
          'instructions' => 'Upload a photo to use for the category.',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_575e15351cc63',
          'label' => 'Category Testimonial',
          'name' => 'category_testimonial',
          'type' => 'relationship',
          'instructions' => 'Select a testimonial to use for the category.',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array (
            0 => 'testimonial',
          ),
          'taxonomy' => array (
          ),
          'filters' => array (
            0 => 'search',
          ),
          'elements' => '',
          'min' => 1,
          'max' => 1,
          'return_format' => 'object',
        ),
        array (
          'key' => 'field_576f0e07d273e',
          'label' => 'Category Link',
          'name' => 'category_link',
          'type' => 'post_object',
          'instructions' => 'Select a page for the category to link to.',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array (
            0 => 'page',
          ),
          'taxonomy' => array (
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'id',
          'ui' => 1,
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-templates/products-page.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_575e0c495eb68',
  'title' => 'Testimonial Fields',
  'fields' => array (
    array (
      'key' => 'field_575e0c5f9ec2c',
      'label' => 'Author Location',
      'name' => 'author_location',
      'type' => 'text',
      'instructions' => 'Enter the author\'s location, city and state.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'testimonial',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_5772d907d3eb4',
  'title' => 'Widget: Bio Image',
  'fields' => array (
    array (
      'key' => 'field_5772dc537621e',
      'label' => 'Bio Image',
      'name' => 'bio_image',
      'type' => 'image',
      'instructions' => 'Upload a photo to use for the bio image.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => 'jpg,jpeg,webp',
    ),
    array (
      'key' => 'field_5772d907d6457',
      'label' => 'Widget Headline',
      'name' => 'widget_headline',
      'type' => 'text',
      'instructions' => 'Enter a headline for the widget.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_5772dc81122e3',
      'label' => 'Widget Text',
      'name' => 'widget_text',
      'type' => 'textarea',
      'instructions' => 'Enter some text to appear below the widget headline.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => 5,
      'new_lines' => 'wpautop',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'widget',
        'operator' => '==',
        'value' => 'bio_image_widget',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_57bc837b8c334',
  'title' => 'Widget: Business Info',
  'fields' => array (
    array (
      'key' => 'field_57bc8427b85bf',
      'label' => 'Business Info',
      'name' => 'business_info',
      'type' => 'textarea',
      'instructions' => 'Enter the business\'s hours and telephone number.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => 3,
      'new_lines' => 'wpautop',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_57bcb8b28cf4a',
      'label' => 'Fine Print Text',
      'name' => 'fine_print_text',
      'type' => 'text',
      'instructions' => 'Enter some fine print text. This could be used to mention the area the business serves or whatever you\'d like.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => 'Servicing the New England Area',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'widget',
        'operator' => '==',
        'value' => 'business_info_widget',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_5772b850207ba',
  'title' => 'Widget: CTA Link',
  'fields' => array (
    array (
      'key' => 'field_5772ba1564506',
      'label' => 'Widget Headline',
      'name' => 'widget_headline',
      'type' => 'text',
      'instructions' => 'Enter a headline for the widget.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_5772ba3464507',
      'label' => 'Widget Text',
      'name' => 'widget_text',
      'type' => 'textarea',
      'instructions' => 'Enter some text to display below the title.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => 5,
      'new_lines' => 'wpautop',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_5772ba6764508',
      'label' => 'CTA Link',
      'name' => 'cta_link',
      'type' => 'post_object',
      'instructions' => 'Select a page for the CTA widget\'s button to link to.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'id',
      'ui' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'widget',
        'operator' => '==',
        'value' => 'cta_link_widget',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_57bdf6bb119ca',
  'title' => 'Widget: Page Link',
  'fields' => array (
    array (
      'key' => 'field_57bdf6bb13e01',
      'label' => 'Widget Headline',
      'name' => 'widget_headline',
      'type' => 'text',
      'instructions' => 'Enter a headline for the widget.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_57bdf6bb13f59',
      'label' => 'Widget Link',
      'name' => 'widget_link',
      'type' => 'post_object',
      'instructions' => 'Select a page for the widget headline to link to.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'id',
      'ui' => 1,
    ),
    array (
      'key' => 'field_57bdfac047b17',
      'label' => 'Widget Icon',
      'name' => 'widget_icon',
      'type' => 'image',
      'instructions' => 'Upload an icon to use before the widget\'s headline.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => 'gif,png,svg,webp',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'widget',
        'operator' => '==',
        'value' => 'page_link_widget',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_5776e53f29ebb',
  'title' => 'Widget: WF Categories',
  'fields' => array (
    array (
      'key' => 'field_5776e53f2e71b',
      'label' => 'Widget Headline',
      'name' => 'widget_headline',
      'type' => 'text',
      'instructions' => 'Enter a headline for the widget.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'widget',
        'operator' => '==',
        'value' => 'category_widget',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_5772c421ef814',
  'title' => 'Widget: WF Recent Posts',
  'fields' => array (
    array (
      'key' => 'field_5772c421f215e',
      'label' => 'Widget Headline',
      'name' => 'widget_headline',
      'type' => 'text',
      'instructions' => 'Enter a headline for the widget.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_5772c4b37b818',
      'label' => 'Number of Posts',
      'name' => 'number_of_posts',
      'type' => 'number',
      'instructions' => 'Enter the number of posts you\'d like to display.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => 2,
      'max' => 5,
      'step' => 1,
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'widget',
        'operator' => '==',
        'value' => 'recent_posts_widget',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_5745145a316b8',
  'title' => 'Page Fields',
  'fields' => array (
    array (
      'key' => 'field_5781676ac7c18',
      'label' => 'Display CTA or Testimonials?',
      'name' => 'display_cta_or_testimonials',
      'type' => 'select',
      'instructions' => 'Check this box if you\'d like to display a CTA or testimonials at the bottom of the page or post.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'cta' => 'CTA',
        'testimonial' => 'Testimonial',
        'testimonial_slider' => 'Testimonial Slider',
      ),
      'default_value' => array (
      ),
      'allow_null' => 1,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_5772d987fc5f1',
      'label' => 'Page CTA',
      'name' => 'page_cta',
      'type' => 'post_object',
      'instructions' => 'Select a CTA to display at the bottom of the page.',
      'required' => 1,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_5781676ac7c18',
            'operator' => '==',
            'value' => 'cta',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'cta',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
    ),
    array (
      'key' => 'field_57c309ee73e03',
      'label' => 'Button Text',
      'name' => 'button_text',
      'type' => 'text',
      'instructions' => 'Enter text for the button. If none is provided, "Read More" will be displayed.',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_5781676ac7c18',
            'operator' => '==',
            'value' => 'cta',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_5770a3ad32aee',
      'label' => 'Page Testimonial',
      'name' => 'page_testimonial',
      'type' => 'post_object',
      'instructions' => 'Select a testimonial to display at the bottom of the page.',
      'required' => 1,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_5781676ac7c18',
            'operator' => '==',
            'value' => 'testimonial',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'testimonial',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
    ),
    array (
      'key' => 'field_57c30e7ba6c44',
      'label' => 'Page Testimonials',
      'name' => 'page_testimonials',
      'type' => 'relationship',
      'instructions' => 'Select the testimonials you\'d like to display in the slider.',
      'required' => 1,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_5781676ac7c18',
            'operator' => '==',
            'value' => 'testimonial_slider',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'testimonial',
      ),
      'taxonomy' => array (
      ),
      'filters' => array (
        0 => 'search',
      ),
      'elements' => '',
      'min' => 2,
      'max' => '',
      'return_format' => 'object',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
      array (
        'param' => 'page_template',
        'operator' => '!=',
        'value' => 'page-templates/home-page.php',
      ),
    ),
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'post',
      ),
    ),
  ),
  'menu_order' => 1,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;